### PR TITLE
Union types without spaces

### PR DESCRIPTION
**Pull request by Nizari**
## Check composer.json

```console
nano /usr/local/lib/php-cs-fixer/composer.json
```

```json
{
    "require": {
        "friendsofphp/php-cs-fixer": "^3.0"
    },
    "config": {
        "platform": {
            "php": "7.4.28"
        }
    }
}
```

## Upgrade composer cs fixer

```console
cd /usr/local/lib/php-cs-fixer
composer update
```

### CODE REVIEW

**Comment by jorisatabix** [comment]
❤️ 

You do have some spacing issue in the files changed it seems. Can you fix that?

**Comment by atabixalex** [comment]
We'll close this after the BE meeting.

Bring. Your. Macbook.

**Comment by jorisatabix** [comment]
Note, we chose this because of VSCode limitations with spaces in union types.

**Comment by atabixalex** [comment]
Everyone updated their composer. 

Only @jeroenatabix needs help with this; something with PHP 7.3 / 7.4

**Comment by Nizari** [comment]
FInal checks where done! merging this now!

**Pull request merged**
